In [1]:
import numpy as np

In [32]:
X = np.random.rand(100, 1)
y = np.random.rand(100, 1)

In [36]:
np.dot(X.T, y)

array([[22.93116416]])

In [37]:
A = np.array([[56.0, 0.0,4.4,68.0],
              [1.2,104.0,52.0,8.0],
              [1.8,135.0,99.0,0.9]])

In [39]:
sum = A.sum(axis=0)

In [41]:
sum

array([ 59. , 239. , 155.4,  76.9])

In [43]:
percentage = 100 * A / sum

In [45]:
percentage

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])